### ISSUE TITLE
Can we add Eindhoven Meetup Logo here too?

### ISSUE THREAD

**Issue by versionbaygt** [matthijscox/EindhovenLogo.jl#1]
It would be great to have another function that also generates the Eindhoven Vibes & Eindhoven Meetup logo:)

**Comment by matthijscox** [comment]
I agree :)

I think we can reuse the official Julia logo code.

For `eindhoven`, we can either use the font, or vectorize the font. In the latter case we can more easily scale to high resolution png sizes.

Final result will be the sum of all three. Julia + eindhoven + vibes.

**Comment by matthijscox** [comment]
Logo code is fully functional, use for example `save_logo("eindhoven.png"; scale=10)`
