### ISSUE TITLE
Check Eindhoven Logo against official logo specs

### ISSUE THREAD

**Issue by versionbaygt** [matthijscox/EindhovenLogo.jl#2]
Here is the official logo specs:

https://www.eindhoven.nl/bestuur-en-beleid/organisatie/logo-en-huisstijl-stad-eindhoven

Here is an email to get them right and permission to use it: [studio@eindhoven.nl](mailto:studio@eindhoven.nl).

**Comment by matthijscox** [comment]
I've sent an email asking for permission and vibes specifications to that address. Let's see :)

**Comment by matthijscox** [comment]
We have permission to use the vibes in our current format!

For the specifications I received the vibes on their grid. I estimated the number of squares and I'll update the code accordingly, but I got pretty close.
![image](https://user-images.githubusercontent.com/17245881/206467499-07e66c30-5f92-425f-afbb-a907a1d0812d.png)
